apiVersion: v1
kind: Service
metadata:
  name: nutrition-ms-service
  labels:
    app: nutrition-ms
spec:
  type: ClusterIP
  selector:
    app: nutrition-ms
  ports:
    - name: http
      port: 81
      targetPort: 8000