apiVersion: v1
kind: Service
metadata:
  name: recipe-ms-service
  labels:
    app: recipe-ms
spec:
  type: ClusterIP
  selector:
    app: recipe-ms
  ports:
    - name: http
      port: 80
      targetPort: 8000